# Generated by Django 5.2.1 on 2025-05-22 07:25
from app.user.models import CustomUser, CustomUserManager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sellerprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', CustomUserManager()),
            ],
        ),
    ]
