# Generated by Django 5.2.1 on 2025-05-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_business_name_customuser_gst_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], max_length=10),
        ),
    ]
