constants = {
    100: "User fetched successfully.",
    101: "User created successfully",
    102: "Logout successfully",
    103: "Password reset link successfully sent",
    104: "Password reset successfully.",
    105: "User profile fetched successfully.",
    106: "User profile updated successfully.",
    107: "Address list fetched successfully.",
    108: "Address created successfully.",
    109: "Address fetched successfully.",
    110: "Address updated successfully.",
    111: "Address deleted successfully.",
    112: "seller approved successfully",

    400: "Refresh token is required", 
    401: "User with this email does not exist.",
    402: "Address not found.",
    403: "User does not exist.",
    404: "Invalid or expired OTP.",
    405: "User not found",
    406: "Seller not found.",
    407: "Seller already approved.",
}